/**
 * Flat role → permission-key grants used exclusively by the seed-org endpoint
 * to write initial RBAC data into the database.
 *
 * The authoritative role definitions live in:
 *   src/features/auth/permissions/admin-access.ts  (Better Auth AC)
 *
 * Keep this in sync with the *AdminRole exports there.
 * Permission keys use "resource.action" notation matching requirePermission().
 */
export const ROLE_GRANTS: Record<string, string[]> = {
    owner: [
        "org.view",
        "org.delete",
        "dashboard.view",
        "settings.view",
        "apikey.manage",
        "marketplace.view",
        "marketplace.edit",
        "marketplace.moderate",
        "marketplace.admin",
        "marketplace.requests",
        "sldb.view",
        "sldb.edit",
        "sldb.admin",
        "blog.view",
        "blog.write",
        "blog.settings.update",
        "wardrobe.view",
        "wardrobe.edit",
        "rbac.manage",
    ],
    developer: [
        "org.view",
        "org.delete",
        "dashboard.view",
        "settings.view",
        "apikey.manage",
        "marketplace.view",
        "marketplace.edit",
        "marketplace.moderate",
        "marketplace.admin",
        "marketplace.requests",
        "sldb.view",
        "sldb.edit",
        "sldb.admin",
        "blog.view",
        "blog.write",
        "blog.settings.update",
        "wardrobe.view",
        "wardrobe.edit",
        "rbac.manage",
    ],
    admin: [
        "org.view",
        "org.delete",
        "dashboard.view",
        "settings.view",
        "apikey.manage",
        "marketplace.view",
        "marketplace.edit",
        "marketplace.moderate",
        "marketplace.admin",
        "marketplace.requests",
        "sldb.view",
        "sldb.edit",
        "sldb.admin",
        "blog.view",
        "blog.write",
        "blog.settings.update",
        "wardrobe.view",
        "wardrobe.edit",
        "rbac.manage",
    ],
    mod: [
        "org.view",
        "dashboard.view",
        "settings.view",
        "apikey.manage",
        "marketplace.view",
        "marketplace.edit",
        "marketplace.moderate",
        "marketplace.admin",
        "marketplace.requests",
        "sldb.view",
        "sldb.edit",
        "sldb.admin",
        "blog.view",
        "blog.write",
        "blog.settings.update",
        "wardrobe.view",
        "wardrobe.edit",
    ],
    trusted: [
        "marketplace.view",
        "marketplace.edit",
        "marketplace.requests",
    ],
    creator: ["sldb.view", "sldb.edit"],
    blogger: ["blog.view", "blog.write"],
    wardrobe: ["wardrobe.view", "wardrobe.edit"],
    user: [
        "dashboard.view",
        "settings.view",
        "apikey.manage",
        "marketplace.view",
        "blog.view",
        "wardrobe.view",
    ],
};
