packages:
  - packages/*
  - scraper-cli
  - shared-data

evergreen-bundled-dependencies:
  - next
  - react
  - react-dom

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
